# Generated by Django 6.0.4 on 2026-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliverynote_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('correction', 'Korrektur/Endern'), ('damage', 'Schaden'), ('return', 'Retour')], max_length=20),
        ),
    ]
